# Generated by Django 3.1.1 on 2020-09-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachermodel',
            options={'ordering': ('-join',)},
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='join',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
