# Generated by Django 3.1.1 on 2020-09-03 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200903_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachermodel',
            old_name='subject_tacher',
            new_name='subject_teacher',
        ),
    ]
